"use strict";
export const translations = {
  pt: {
    appTitle: "AMI Planner",
    tagline: "A M\xEDdia da Igreja",
    // Menu
    menuAbout: "Quem Somos",
    menuHome: "Home",
    menuBudget: "Fazer Or\xE7amento",
    menuGrowth: "Proje\xE7\xE3o de Crescimento",
    menuStart: "Como Come\xE7ar",
    // Admin/About
    aboutLabel: "Quem Somos",
    aboutSec1Title: "O que \xE9 o AMI Planner?",
    aboutSec1Text1: "O AMI Planner \xE9 uma extens\xE3o gratu\xEDta desenvolvida pela A Midia da Igreja fundada pelo Job Zezz, diretor do Departamento de M\xEDdia da ",
    aboutSec1Link1Text: "ADP Minist\xE9rio Comunh\xE3o e Plenitude",
    aboutSec1Link1Url: "https://adpmcp.org",
    aboutSec1Text2: " e da ",
    aboutSec1Link2Text: "Cruzada Evangelistica Cristo Vive",
    aboutSec1Link2Url: "https://adpmcp.org/cristovive",
    aboutSec1Text3: ", especialista em design institucional e de marketing digital com mais de 15 anos de experi\xEAncia.",
    aboutSec2Title: "Quem \xE9 o Job Zezz?",
    aboutSec2P1: "Escritor, criador de conte\xFAdo crist\xE3o, artista e vision\xE1rio, tem como prop\xF3sito fazer Cristo ser conhecido atrav\xE9s da m\xEDdia, arte e entretenimento \u2014 livros, m\xFAsicas, mensagens e conte\xFAdos que inspiram, curam e edificam. Criador do Encontradamente Kids, The Church Media (A M\xEDdia da Igreja) e Seeding Hope.",
    aboutSec2P2: "Com uma trajet\xF3ria marcada pela f\xE9, Job Zezz acredita que a arte \xE9 uma linguagem divina: uma express\xE3o capaz de dar vida, transformar cora\xE7\xF5es e restaurar prop\xF3sitos. Em cada projeto, ele une espiritualidade e criatividade, construindo pontes entre o Evangelho e a cultura contempor\xE2nea.",
    aboutSec2P3: "AUTOR DOS LIVROS: Deus Ainda Fala Connosco, Se eu Fizer Sentir, C\xEDclo - Depois da Luz, Minist\xE9rio da M\xEDdia, Os 7 Pilares da Sociedade e Deus Ainda Fala Connosco para Crian\xE7as.",
    aboutSec2P4: "Mais do que entreter, queremos despertar gera\xE7\xF5es para voltarmos ao Monte Santo do Senhor, chamando o mundo a viver novamente sob a presen\xE7a e dire\xE7\xE3o de Deus.",
    // Partners
    partnerConsulting: "Vai uma Consultoria?",
    partnerBook: "Adquira o Livro",
    partnerBookDesc: "O Minist\xE9rio da M\xEDdia",
    partnerWorkshop: "Escola da M\xEDdia",
    partnerWorkshopDesc: "Treinamento intensivo",
    partnerNonprofit: "Recursos Nonprofit",
    partnerNonprofitDesc: "Programas ilimitado para CRM, Finan\xE7as, Canvas Pro, Adobe Express Google, Microsoft e muitos mais com desconto de at\xE9 90%",
    // UI
    languageSwitcher: "Idioma:",
    generating: "Desenhando seu projeto ideal...",
    analyzing: "Analisando perfil tecnol\xF3gico...",
    generateBtn: "Gerar Projeto AV",
    analyzeBtn: "Analisar M\xE9tricas",
    downloadPDF: "Baixar em PDF",
    footer: "A Midia da Igreja (C) Desde 2026",
    // Budget Form
    formTitle: "Contexto do Minist\xE9rio",
    focus: "Foco",
    focusMedia: "M\xEDdia da Igreja",
    focusSound: "Som da Igreja",
    churchName: "Nome da Igreja",
    members: "Membros Atuais",
    growth: "Proje\xE7\xE3o de Crescimento",
    currentLevel: "Equipamento Atual",
    budget: "Or\xE7amento Dispon\xEDvel",
    budgetPlaceholder: "Ex: 15.000",
    location: "Pa\xEDs / Regi\xE3o",
    errorRequired: "Preencha todos os campos obrigat\xF3rios.",
    growthStable: "Crescimento Est\xE1vel",
    growthModerate: "Moderado (at\xE9 50%)",
    growthHigh: "Acelerado (Dobrar ou mais)",
    mediaLevel0: "N\xEDvel 0 (Nenhum / Come\xE7ando do zero)",
    mediaLevel1: "N\xEDvel 1 (B\xE1sico - C\xE2mera b\xE1sica, luz simples)",
    mediaLevel2: "N\xEDvel 2 (Intermedi\xE1rio - Multic\xE2mera, streaming, ilumin. b\xE1sica)",
    mediaLevel3: "N\xEDvel 3 (Avan\xE7ado - C\xE2meras de cinema, Pain\xE9is LED, broadcast)",
    soundLevel0: "N\xEDvel 0 (Nenhum / Come\xE7ando do zero)",
    soundLevel1: "N\xEDvel 1 (B\xE1sico - Caixas ativas, mesa anal\xF3gica)",
    soundLevel2: "N\xEDvel 2 (Intermedi\xE1rio - Mesa digital, monitora\xE7\xE3o simples)",
    soundLevel3: "N\xEDvel 3 (Avan\xE7ado - Line array, rede Dante, monitora\xE7\xE3o pessoal)",
    locBR: "Brasil (PT) - R$",
    locPT: "Portugal (PT) - \u20AC",
    locAO: "Angola (PT) - Kz",
    locCV: "Cabo Verde (PT) - cve",
    locMZ: "Mo\xE7ambique (PT) - MT",
    locEN: "US / Global (EN) - $",
    locFR: "Fran\xE7a / \xC1frica Franc\xF3fona (FR) - \u20AC",
    locES: "Espanha / LatAm (ES) - \u20AC/$",
    resultsTitle: "Seu Projeto Recomendado",
    summaryLabel: "Estrat\xE9gia Recomendada",
    estimatedTotal: "Custo Estimado Total",
    buyLink: "Comprar",
    emptyBudget: "Aguardando Par\xE2metros",
    emptyBudgetDesc: "Preencha os dados no formul\xE1rio para gerar uma cota\xE7\xE3o.",
    // Growth Simulator
    socialLink: "Link da Rede Social Principal",
    socialPlaceholder: "Ex: instagram.com/igreja",
    growthResultsTitle: "Diagn\xF3stico e Solu\xE7\xF5es",
    metricsLabel: "M\xE9tricas Diagnosticadas",
    solutionsLabel: "Solu\xE7\xF5es Recomendadas",
    // Home & Start
    homeWelcome: "Bem-vindo ao AMI Planner",
    homeDesc: "A plataforma oficial d'A M\xEDdia da Igreja para planejamento financeiro, audiovisual e diagn\xF3stico de redes sociais. Auxiliamos minist\xE9rios a aplicarem recursos com intelig\xEAncia.",
    startTitle: "Fundamentos do Minist\xE9rio da M\xEDdia",
    startContent: [
      {
        title: "1\xBA Ora\xE7\xE3o e Jejum",
        text: "A m\xEDdia eficaz come\xE7a nos joelhos. Sem o alinhamento com a vontade de Deus, as plataformas e os conte\xFAdos podem ter milh\xF5es de views, engajamento e seguidores, mas n\xE3o gerar\xE3o transforma\xE7\xE3o genu\xEDna, sem contar que \xE9 atrav\xE9s da m\xEDdia que enfrentamos direitamente os principados e potestades das cidades, prov\xEDncias e na\xE7\xF5es aonde chegam os nossos conte\xFAdos. Por isso, antes de pegar um smartphone, c\xE2mera, criar uma rede social, etc., precisamos ter: Identidade e Car\xE1ter, Un\xE7\xE3o, Discernimento, Lideran\xE7a do Esp\xEDrito Santo, Sabedoria Divina, intercess\xE3o forte que gera crescimento num\xE9rico, espiritual, financeiro e social."
      },
      {
        title: "2. Produ\xE7\xE3o Audiovisual",
        text: "Dominar a t\xE9cnica do audiovisual completo permite que o mover do Esp\xEDrito n\xE3o seja interrompido por falhas humanas ou m\xE1 qualidade. Tudo que precisamos fazer \xE9 entender com profundidade:",
        subItems: [
          "1. Os tr\xEAs processos do AV: Pr\xE9 Produ\xE7\xE3o, Produ\xE7\xE3o e P\xF3s Produ\xE7\xE3o;",
          "2. Pilares da Fotografia (Tri\xE2ngulo da Exposi\xE7\xE3o): Equil\xEDbrio entre ISO (sensibilidade), Velocidade do Obturador (movimento) e Abertura (luz e desfoque).",
          "3. Ilumina\xE7\xE3o: Uso da Luz Principal, Luz de Preenchimento e Contra luz para dar tridimensionalidade ao sujeito.",
          "4. Enquadramento e \xC2ngulos: Uso de planos (Geral, M\xE9dio, Close-up) e \xE2ngulos (Plong\xEA e Contra-Plong\xEA) para guiar a emo\xE7\xE3o do espectador.",
          "5. Roteiro: O roteiro \xE9 o guia que evita gastos desnecess\xE1rios e foca no prop\xF3sito da obra.",
          "6. Formatos: Produ\xE7\xE3o de document\xE1rios, curtas-metragens, testemunhos e podcasts para ensinar a palavra 24h por dia.",
          "7. Livestreaming, Podcast e/ou Testemunhos: Transmiss\xE3o simples (direta por apps) ou avan\xE7ada (multic\xE2mera via OBS Studio, Wirecast, vMix ou ATEM).",
          "8. Produ\xE7\xE3o com IA (Informa\xE7\xE3o externa): Ferramentas como CapCut, QusoAI, Opusclip, para edi\xE7\xE3o r\xE1pida de shorts, ou Nano Banana, Midjourney, etc., para gera\xE7\xE3o de imagens conceituais e Runway para v\xEDdeos."
        ]
      },
      {
        title: "3. Produ\xE7\xE3o Gr\xE1fica",
        text: "O design n\xE3o \xE9 apenas est\xE9tica, \xE9 estrat\xE9gia de comunica\xE7\xE3o. Ele vai muito mais do que fazer um flyer, banner, etc., ele \xE9 gancho que atrai a aten\xE7\xE3o dos seguidores, em outras palavras, \xE9 a vitrine da institui\xE7\xE3o. Uma igreja que n\xE3o investe em qualidade de design, est\xE1 fadada a atrair apenas pessoas desorganizadas e de baixo escal\xE3o. Quando falamos de designer estamos a falar da aplica\xE7\xE3o dos seus princ\xEDpios para estabelecer:",
        subItems: [
          "a) Branding e Identidade Visual: Conjunto de elementos (logotipo, cores, tipografia) que representam a miss\xE3o e os valores da Igreja.",
          "b) Designer Institucional e de Eventos: Uso de templates e manuais de marca para garantir consist\xEAncia visual em todas as frentes.",
          "c) Webdesign: O site oficial deve ser o reposit\xF3rio da ess\xEAncia ministerial, funcionando como uma vitrine organizada.",
          "d) Fundamentos: Aplica\xE7\xE3o de propor\xE7\xF5es, composi\xE7\xE3o, margens de seguran\xE7a, contraste, equilibrio, repeti\xE7\xE3o, psicologia das cores e regras tipogr\xE1ficas para conforto na leitura."
        ]
      },
      {
        title: "4. Editorial e Copywriting",
        text: "A Produ\xE7\xE3o Editorial \xE9 a materializa\xE7\xE3o verbal da estrat\xE9gia da marca (Igreja), sendo crucial para o di\xE1logo e a doutrina\xE7\xE3o (ensino).",
        subItems: [
          "a) Conte\xFAdo e Copywriter (Reda\xE7\xE3o): O conte\xFAdo deve ser de qualidade e alinhado aos valores \xE9ticos e crist\xE3os. O tom de voz e o universo verbal da marca precisam ser definidos. A linguagem verbal escrita \xE9 vital na internet. O minist\xE9rio deve ter jornalistas, linguistas e redatores para o desenvolvimento do conte\xFAdo.",
          "b) Literatura: A Igreja precisa publicar e divulgar suas ideias. O uso da boa imprensa e a produ\xE7\xE3o de revistas informativas, folhetos, agendas semanais, livros, s\xE3o formas de ampliar o di\xE1logo e a informa\xE7\xE3o, inclusive com a comunidade externa.",
          "c) Intera\xE7\xE3o com o P\xFAblico nas Plataformas Sociais: \xC9 essencial fomentar a cria\xE7\xE3o de outras narrativas que gerem influ\xEAncia e engajamento. A comunica\xE7\xE3o exige participa\xE7\xE3o, co-autoria e uma rede de rela\xE7\xF5es. O minist\xE9rio deve escutar atentamente a opini\xE3o p\xFAblica e promover o di\xE1logo cont\xEDnuo."
        ]
      },
      {
        title: "5. Gest\xE3o e Estrat\xE9gia",
        text: "O minist\xE9rio deve ser gerido com profissionalismo e vis\xE3o estrat\xE9gica.",
        subItems: [
          "a) Benchmarking: Analisar as melhores pr\xE1ticas de outras igrejas e grupos de comunica\xE7\xE3o para inovar constantemente.",
          "b) Marketing Digital e Redes Sociais: Gest\xE3o inteligente do Facebook, Instagram, Youtube e TikTok, focando em m\xE9tricas de alcance e, principalmente, convers\xE3o.",
          "c) M\xE9tricas (KPIs): Acompanhar mensalmente se a mensagem est\xE1 alcan\xE7ando o p\xFAblico-alvo.",
          "d) Estrat\xE9gias de Crescimento",
          "e) Ferramentas Non-Profit",
          "f) Comunidade Global Digital: Criar um ambiente de intera\xE7\xE3o que v\xE1 al\xE9m da transmiss\xE3o, fazendo o espectador sentir-se parte do corpo de Cristo atrav\xE9s de grupos e respostas ativas."
        ]
      }
    ],
    // Consulting Pop-up
    consultingTitle: "Vai uma Consultoria?",
    consultingDesc: "Preencha os dados abaixo e escolha como deseja nos contatar.",
    cName: "Seu Nome",
    cChurch: "Sua Igreja",
    cPhone: "Telefone",
    cNeed: "Sua Necessidade",
    btnEmail: "Entrar em contato por E-mail",
    btnWhatsapp: "Entrar em contato por WhatsApp",
    cancel: "Cancelar"
  },
  en: {
    appTitle: "AMI Planner",
    tagline: "Church Media Team",
    menuAbout: "About Us",
    menuHome: "Home",
    menuBudget: "Media Budgeting",
    menuGrowth: "Growth Projection",
    menuStart: "How to Start",
    languageSwitcher: "Language:",
    generating: "Designing ideal project...",
    analyzing: "Analyzing metrics...",
    generateBtn: "Generate Project",
    analyzeBtn: "Analyze Metrics",
    downloadPDF: "Download PDF",
    footer: "A Midia da Igreja (C) Since 2026",
    formTitle: "Ministry Context",
    focus: "Focus",
    focusMedia: "Church Media",
    focusSound: "Church Sound",
    churchName: "Church Name",
    members: "Current Attendance",
    growth: "Growth Projection",
    currentLevel: "Current Equipment",
    budget: "Available Budget",
    budgetPlaceholder: "e.g., 15000",
    location: "Country / Region",
    errorRequired: "Please fill in all required fields.",
    growthStable: "Stable Growth",
    growthModerate: "Moderate (up to 50%)",
    growthHigh: "Accelerated (Double+)",
    mediaLevel0: "Level 0 (Starting from scratch)",
    mediaLevel1: "Level 1 (Basic Camera, simple lighting)",
    mediaLevel2: "Level 2 (Intermediate - Multi-cam, streaming)",
    mediaLevel3: "Level 3 (Advanced - Cinema cams, LED walls)",
    soundLevel0: "Level 0 (Starting from scratch)",
    soundLevel1: "Level 1 (Basic - Active speakers, analog mixer)",
    soundLevel2: "Level 2 (Intermediate - Digital mixer, basic monitors)",
    soundLevel3: "Level 3 (Advanced - Line array, Dante, personal monitoring)",
    locBR: "Brazil (PT) - R$",
    locPT: "Portugal (PT) - \u20AC",
    locAO: "Angola (PT) - Kz",
    locCV: "Cape Verde (PT) - cve",
    locMZ: "Mozambique (PT) - MT",
    locEN: "US / Global (EN) - $",
    locFR: "France / Francophone (FR) - \u20AC",
    locES: "Spain / LatAm (ES) - \u20AC/$",
    resultsTitle: "Recommended Setup",
    summaryLabel: "Recommended Strategy",
    estimatedTotal: "Estimated Total Cost",
    buyLink: "Buy Link",
    emptyBudget: "Waiting for Parameters",
    emptyBudgetDesc: "Fill the form to generate a quote.",
    socialLink: "Primary Social Media Link",
    socialPlaceholder: "e.g., instagram.com/church",
    growthResultsTitle: "Diagnostic & Solutions",
    metricsLabel: "Diagnosed Metrics",
    solutionsLabel: "Recommended Solutions",
    homeWelcome: "Welcome to AMI Planner",
    homeDesc: "The official planning platform for financial, audiovisual, and social media diagnostics. Assisting ministries in applying resources smartly.",
    startTitle: "Media Ministry Fundamentals",
    startContent: [
      {
        title: "1\xBA Prayer and Fasting",
        text: "Effective media starts on your knees. Without alignment with God's will, platforms and content might get millions of views but no genuine transformation. Therefore, before taking a smartphone or camera, we need: Identity, Character, Anointing, Discernment, Holy Spirit's guidance, and strong intercession."
      },
      {
        title: "2. AV Production",
        text: "Mastering audiovisual tech ensures the Spirit's movement isn't interrupted by technical failures. Understand deeply:",
        subItems: [
          "1. 3 AV Processes: Pre-production, Production, Post-production.",
          "2. Photography Pillars: ISO, Shutter Speed, Aperture.",
          "3. Lighting: Key, Fill, and Backlight.",
          "4. Framing & Angles: Wide, Medium, Close-up, High/Low angles.",
          "5. Scripting: Focused purpose and budget control.",
          "6. Formats: Docs, short-films, testimonies, podcasts.",
          "7. Livestreaming: Simple or Advanced (OBS, ATEM).",
          "8. AI Tools: CapCut, Opusclip, Midjourney."
        ]
      },
      {
        title: "3. Graphic Production",
        text: "Design is not just aesthetics; it's communication strategy. It's the showcase of the institution.",
        subItems: [
          "a) Branding & Identity: Logos, colors, typography.",
          "b) Institutional Design: Templates and brand manuals.",
          "c) Webdesign: Official site as the organized showcase.",
          "d) Fundamentals: Proportions, contrast, balance, color psychology."
        ]
      },
      {
        title: "4. Editorial and Copywriting",
        text: "Editorial production is the verbal materialization of the brand strategy (Church).",
        subItems: [
          "a) Content & Copywriter: Quality content aligned with Christian ethics.",
          "b) Literature: Informative magazines, weekly planners, books.",
          "c) Social Media Interaction: Fostering dialogue, listening to public opinion, active engagement."
        ]
      },
      {
        title: "5. Management & Strategy",
        text: "The ministry must be managed professionally with strategic vision.",
        subItems: [
          "a) Benchmarking: Analyzing best practices from other churches.",
          "b) Digital Marketing: Smart management of Facebook, Instagram, YouTube, TikTok.",
          "c) KPIs: Tracking message reach monthly.",
          "d) Growth Strategies.",
          "e) Non-Profit Tools.",
          "f) Global Digital Community: Active discipleship beyond just broadcasting."
        ]
      }
    ],
    consultingTitle: "Need Consulting?",
    consultingDesc: "Fill the details and choose how you want to be contacted.",
    cName: "Your Name",
    cChurch: "Your Church",
    cPhone: "Phone",
    cNeed: "Your Need",
    btnEmail: "Contact via Email",
    btnWhatsapp: "Contact via WhatsApp",
    cancel: "Cancel",
    partnerConsulting: "Need Consulting?",
    partnerBook: "Get the Book",
    partnerBookDesc: "The Media Ministry",
    partnerWorkshop: "Media School",
    partnerWorkshopDesc: "Intensive Training",
    partnerNonprofit: "Nonprofit Resources",
    partnerNonprofitDesc: "Unlimited programs for CRM, Finances, Canvas Pro, Adobe Express, Google, Microsoft and more with up to 90% discount",
    aboutLabel: "About Us",
    aboutSec1Title: "What is AMI Planner?",
    aboutSec1Text1: "AMI Planner is a free extension developed by A Midia da Igreja founded by Job Zezz, Media Department Director at ",
    aboutSec1Link1Text: "ADP Minist\xE9rio Comunh\xE3o e Plenitude",
    aboutSec1Link1Url: "https://adpmcp.org",
    aboutSec1Text2: " and ",
    aboutSec1Link2Text: "Cruzada Evangelistica Cristo Vive",
    aboutSec1Link2Url: "https://adpmcp.org/cristovive",
    aboutSec1Text3: ", an institutional design and digital marketing specialist with over 15 years of experience.",
    aboutSec2Title: "Who is Job Zezz?",
    aboutSec2P1: "Writer, Christian content creator, artist, and visionary, his purpose is to make Christ known through media, art, and entertainment \u2014 books, music, messages, and content that inspire, heal, and edify. Creator of Encontradamente Kids, The Church Media, and Seeding Hope.",
    aboutSec2P2: "With a journey marked by faith, Job Zezz believes art is a divine language: an expression capable of giving life, transforming hearts, and restoring purposes. In every project, he unites spirituality and creativity, building bridges between the Gospel and contemporary culture.",
    aboutSec2P3: "AUTHOR OF THE BOOKS: Deus Ainda Fala Connosco, Se eu Fizer Sentir, C\xEDclo - Depois da Luz, Minist\xE9rio da M\xEDdia, Os 7 Pilares da Sociedade, and Deus Ainda Fala Connosco para Crian\xE7as.",
    aboutSec2P4: "More than entertaining, we want to awaken generations to return to the Holy Mountain of the Lord, calling the world to live again under the presence and direction of God."
  },
  es: {
    appTitle: "AMI Planner",
    tagline: "El Ministerio de Medios",
    menuAbout: "Qui\xE9nes Somos",
    menuHome: "Inicio",
    menuBudget: "Presupuesto de Medios",
    menuGrowth: "Proyecci\xF3n Crecimiento",
    menuStart: "C\xF3mo Empezar",
    languageSwitcher: "Idioma:",
    generating: "Dise\xF1ando proyecto...",
    analyzing: "Analizando m\xE9tricas...",
    generateBtn: "Generar Proyecto",
    analyzeBtn: "Analizar M\xE9tricas",
    downloadPDF: "Descargar en PDF",
    footer: "A Midia da Igreja (C) Desde 2026",
    formTitle: "Contexto del Ministerio",
    focus: "Enfoque",
    focusMedia: "Medios de la Iglesia",
    focusSound: "Sonido de la Iglesia",
    churchName: "Nombre de la Iglesia",
    members: "Asistencia Actual",
    growth: "Proyecci\xF3n",
    currentLevel: "Equipamiento",
    budget: "Presupuesto Disponible",
    budgetPlaceholder: "Ej: 15000",
    location: "Regi\xF3n / Pa\xEDs",
    errorRequired: "Rellena los campos obligatorios.",
    growthStable: "Estable",
    growthModerate: "Moderado (hasta 50%)",
    growthHigh: "Acelerado (Doble+)",
    mediaLevel0: "Nivel 0 (Desde cero)",
    mediaLevel1: "Nivel 1 (B\xE1sico)",
    mediaLevel2: "Nivel 2 (Intermedio)",
    mediaLevel3: "Nivel 3 (Avanzado)",
    soundLevel0: "Nivel 0 (Desde cero)",
    soundLevel1: "Nivel 1 (B\xE1sico)",
    soundLevel2: "Nivel 2 (Intermedio)",
    soundLevel3: "Nivel 3 (Avanzado)",
    locBR: "Brasil (PT) - R$",
    locPT: "Portugal (PT) - \u20AC",
    locAO: "Angola (PT) - Kz",
    locCV: "Cabo Verde (PT) - cve",
    locMZ: "Mozambique (PT) - MT",
    locEN: "US / Global (EN) - $",
    locFR: "Francia (FR) - \u20AC",
    locES: "Espa\xF1a / LatAm (ES) - \u20AC/$",
    resultsTitle: "Configuraci\xF3n Recomendada",
    summaryLabel: "Estrategia",
    estimatedTotal: "Costo Total",
    buyLink: "Comprar",
    emptyBudget: "Esperando Par\xE1metros",
    emptyBudgetDesc: "Llena el formulario para cotizar.",
    socialLink: "Enlace de Redes Sociales",
    socialPlaceholder: "Ej: instagram.com/iglesia",
    growthResultsTitle: "Diagn\xF3stico y Soluciones",
    metricsLabel: "M\xE9tricas Diagnosticadas",
    solutionsLabel: "Soluciones Recomendadas",
    homeWelcome: "Bienvenido a AMI Planner",
    homeDesc: "Plataforma oficial para planificaci\xF3n financiera y de medios.",
    startTitle: "Fundamentos de Medios",
    startContent: [
      {
        title: "1\xBA Oraci\xF3n y Ayuno",
        text: "Los medios eficaces comienzan de rodillas. Necesitamos: Identidad, Car\xE1cter, Unci\xF3n e intercesi\xF3n fuerte que genere crecimiento espiritual y num\xE9rico."
      },
      {
        title: "2. Producci\xF3n Audiovisual",
        text: "Dominar la t\xE9cnica asegura que el mover del Esp\xEDritu no se interrumpa:",
        subItems: [
          "1. Tres Procesos AV: Pre-producci\xF3n, Producci\xF3n y Post-producci\xF3n.",
          "2. Fotograf\xEDa: ISO, Obturador, Apertura",
          "3. Iluminaci\xF3n y Encuadre.",
          "4. Formatos y Guiones.",
          "5. Streaming (OBS, ATEM) e IA."
        ]
      },
      {
        title: "3. Producci\xF3n Gr\xE1fica",
        text: "El dise\xF1o es estrategia. Es la vitrina de la instituci\xF3n:",
        subItems: [
          "a) Branding.",
          "b) Dise\xF1o de Eventos.",
          "c) Webdesign.",
          "d) Fundamentos del color y repetici\xF3n."
        ]
      },
      {
        title: "4. Editorial y Copywriting",
        text: "La materializaci\xF3n verbal de la estrategia:",
        subItems: [
          "a) Redacci\xF3n \xE9tica y cristiana.",
          "b) Producci\xF3n de revistas y literatura.",
          "c) Interacci\xF3n activa con el p\xFAblico."
        ]
      },
      {
        title: "5. Gesti\xF3n y Estrategia",
        text: "Manejo profesional del ministerio:",
        subItems: [
          "a) Redes Sociales e Innovaci\xF3n.",
          "b) KPIs.",
          "c) Comunidad Global Digital."
        ]
      }
    ],
    consultingTitle: "\xBFNecesitas Consultor\xEDa?",
    consultingDesc: "Llena tus datos y elige c\xF3mo contactarnos.",
    cName: "Tu Nombre",
    cChurch: "Tu Iglesia",
    cPhone: "Tel\xE9fono",
    cNeed: "Tu Necesidad",
    btnEmail: "Contactar por Email",
    btnWhatsapp: "Contactar por WhatsApp",
    cancel: "Cancelar",
    partnerConsulting: "\xBFNecesitas Consultor\xEDa?",
    partnerBook: "Adquiere el Libro",
    partnerBookDesc: "El Ministerio de Medios",
    partnerWorkshop: "Escuela de Medios",
    partnerWorkshopDesc: "Capacitaci\xF3n intensiva",
    partnerNonprofit: "Recursos para ONGs",
    partnerNonprofitDesc: "Programas ilimitados para CRM, Finanzas, Canvas Pro, Adobe Express, Google, Microsoft y m\xE1s con hasta 90% de descuento",
    aboutLabel: "Qui\xE9nes Somos",
    aboutSec1Title: "\xBFQu\xE9 es AMI Planner?",
    aboutSec1Text1: "AMI Planner es una extensi\xF3n gratuita desarrollada por A Midia da Igreja fundada por Job Zezz, director del Departamento de Medios de ",
    aboutSec1Link1Text: "ADP Minist\xE9rio Comunh\xE3o e Plenitude",
    aboutSec1Link1Url: "https://adpmcp.org",
    aboutSec1Text2: " y la ",
    aboutSec1Link2Text: "Cruzada Evangelistica Cristo Vive",
    aboutSec1Link2Url: "https://adpmcp.org/cristovive",
    aboutSec1Text3: ", especialista en dise\xF1o institucional y marketing digital con m\xE1s de 15 a\xF1os de experiencia.",
    aboutSec2Title: "\xBFQui\xE9n es Job Zezz?",
    aboutSec2P1: "Escritor, creador de contenido cristiano, artista y visionario, su prop\xF3sito es dar a conocer a Cristo a trav\xE9s de los medios, el arte y el entretenimiento.",
    aboutSec2P2: "Con una trayectoria marcada por la fe, Job Zezz cree que el arte es un lenguaje divino capaz de dar vida, transformar corazones y restaurar prop\xF3sitos.",
    aboutSec2P3: "AUTOR DE LOS LIBROS: Deus Ainda Fala Connosco, Se eu Fizer Sentir, C\xEDclo - Depois da Luz, Minist\xE9rio da M\xEDdia, Os 7 Pilares da Sociedade y Deus Ainda Fala Connosco para Crian\xE7as.",
    aboutSec2P4: "M\xE1s que entretener, queremos despertar a las generaciones para volver al Monte Santo del Se\xF1or, llamando al mundo a vivir nuevamente bajo la direcci\xF3n de Dios."
  },
  fr: {
    appTitle: "AMI Planner",
    tagline: "M\xE9dias de l'\xC9glise",
    menuAbout: "\xC0 Propos",
    menuHome: "Accueil",
    menuBudget: "Budget Audiovisuel",
    menuGrowth: "Croissance",
    menuStart: "Comment Commencer",
    languageSwitcher: "Langue:",
    generating: "Conception du projet...",
    analyzing: "Analyse des m\xE9triques...",
    generateBtn: "G\xE9n\xE9rer Projet",
    analyzeBtn: "Analyser",
    downloadPDF: "T\xE9l\xE9charger PDF",
    footer: "A Midia da Igreja (C) Depuis 2026",
    formTitle: "Contexte du Minist\xE8re",
    focus: "Focus",
    focusMedia: "M\xE9dias de l'\xC9glise",
    focusSound: "Son de l'\xC9glise",
    churchName: "Nom de l'\xC9glise",
    members: "Assistance Actuelle",
    growth: "Projection",
    currentLevel: "\xC9quipement actuel",
    budget: "Budget",
    budgetPlaceholder: "Ex: 15000",
    location: "R\xE9gion / Pays",
    errorRequired: "Remplissez les champs obligatoires.",
    growthStable: "Stable",
    growthModerate: "Mod\xE9r\xE9 (50%)",
    growthHigh: "Acc\xE9l\xE9r\xE9 (Double+)",
    mediaLevel0: "Niveau 0 (Z\xE9ro)",
    mediaLevel1: "Niveau 1 (Basique)",
    mediaLevel2: "Niveau 2 (Interm\xE9diaire)",
    mediaLevel3: "Niveau 3 (Avanc\xE9)",
    soundLevel0: "Niveau 0 (Z\xE9ro)",
    soundLevel1: "Niveau 1 (Basique)",
    soundLevel2: "Niveau 2 (Interm\xE9diaire)",
    soundLevel3: "Niveau 3 (Avanc\xE9)",
    locBR: "Br\xE9sil (PT) - R$",
    locPT: "Portugal (PT) - \u20AC",
    locAO: "Angola (PT) - Kz",
    locCV: "Cap-Vert (PT) - cve",
    locMZ: "Mozambique (PT) - MT",
    locEN: "US / Global (EN) - $",
    locFR: "France / Afrique (FR) - \u20AC",
    locES: "Espagne / LatAm (ES) - \u20AC/$",
    resultsTitle: "Configuration Recommand\xE9e",
    summaryLabel: "Strat\xE9gie",
    estimatedTotal: "Co\xFBt Total",
    buyLink: "Acheter",
    emptyBudget: "En attente de param\xE8tres",
    emptyBudgetDesc: "Remplissez le formulaire.",
    socialLink: "Lien R\xE9seaux Sociaux",
    socialPlaceholder: "Ex: instagram.com/eglise",
    growthResultsTitle: "Diagnostic et Solutions",
    metricsLabel: "M\xE9triques",
    solutionsLabel: "Solutions Recommand\xE9es",
    homeWelcome: "Bienvenue sur AMI Planner",
    homeDesc: "Plateforme officielle de planification financi\xE8re et m\xE9dias de l'\xE9glise.",
    startTitle: "Principes Fondamentaux",
    startContent: [
      {
        title: "1\xBA Pri\xE8re et Je\xFBne",
        text: "Le fondement spirituel avant toute action technique."
      },
      {
        title: "2. Production AV",
        text: "Trois Processus: Pr\xE9-production, Production et Post-production. Sons, vid\xE9os, lumi\xE8res."
      },
      {
        title: "3. Production Graphique",
        text: "Branding et Identit\xE9 Visuelle. Conception d'\xE9v\xE9nements et de sites web."
      },
      {
        title: "4. R\xE9daction",
        text: "Contenu de qualit\xE9, align\xE9 sur les valeurs chr\xE9tiennes. Interaction publique."
      },
      {
        title: "5. Gestion et Strat\xE9gie",
        text: "Analyse, KPI, strat\xE9gies de croissance et communaut\xE9 num\xE9rique globale."
      }
    ],
    consultingTitle: "Besoin de Conseil?",
    consultingDesc: "Remplissez vos coordonn\xE9es.",
    cName: "Votre Nom",
    cChurch: "Votre \xC9glise",
    cPhone: "T\xE9l\xE9phone",
    cNeed: "Votre Besoin",
    btnEmail: "Contacter par Email",
    btnWhatsapp: "Contacter par WhatsApp",
    cancel: "Annuler",
    partnerConsulting: "Besoin de Conseil?",
    partnerBook: "Obtenir le Livre",
    partnerBookDesc: "Le Minist\xE8re des M\xE9dias",
    partnerWorkshop: "\xC9cole des M\xE9dias",
    partnerWorkshopDesc: "Formation intensive",
    partnerNonprofit: "Ressources Nonprofit",
    partnerNonprofitDesc: "Programmes illimit\xE9s pour CRM, Finances, Canvas Pro, Adobe Express, Google, Microsoft et plus avec jusqu'\xE0 90% de r\xE9duction",
    aboutLabel: "\xC0 Propos",
    aboutSec1Title: "Qu'est-ce que AMI Planner?",
    aboutSec1Text1: "AMI Planner est une extension gratuite d\xE9velopp\xE9e par A Midia da Igreja fond\xE9e par Job Zezz, Directeur du D\xE9partement M\xE9dia de ",
    aboutSec1Link1Text: "ADP Minist\xE9rio Comunh\xE3o e Plenitude",
    aboutSec1Link1Url: "https://adpmcp.org",
    aboutSec1Text2: " et la ",
    aboutSec1Link2Text: "Cruzada Evangelistica Cristo Vive",
    aboutSec1Link2Url: "https://adpmcp.org/cristovive",
    aboutSec1Text3: ", un sp\xE9cialiste en design institutionnel et marketing digital avec plus de 15 ans d'exp\xE9rience.",
    aboutSec2Title: "Qui est Job Zezz?",
    aboutSec2P1: "\xC9crivain, cr\xE9ateur de contenu chr\xE9tien, artiste et visionnaire, son but est de faire conna\xEEtre le Christ \xE0 travers les m\xE9dias et les arts.",
    aboutSec2P2: "Avec un parcours marqu\xE9 par la foi, Job Zezz croit que l'art est un langage divin: une expression capable de donner la vie et de transformer les c\u0153urs.",
    aboutSec2P3: "AUTEUR DES LIVRES: Deus Ainda Fala Connosco, Se eu Fizer Sentir, C\xEDclo - Depois da Luz, Minist\xE9rio da M\xEDdia, Os 7 Pilares da Sociedade et Deus Ainda Fala Connosco para Crian\xE7as.",
    aboutSec2P4: "Plus que de divertir, nous voulons \xE9veiller les g\xE9n\xE9rations \xE0 retourner \xE0 la Sainte Montagne du Seigneur."
  }
};
